version: '3'

services: 
  nginx:
    image: nginx:latest
    volumes: 
      - ./:/var/www/
      - ./storage:/var/www/storage
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8876:80
    container_name: task_list_nginx
    depends_on: 
     - app

  app: 
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes: 
      - ./:/var/www/
    depends_on: 
      - db
    container_name: task_list_app

  db:
    image: postgres:17.2
    restart: always
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: task_list
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 8101:5432
    container_name: task_list_db
